### ISSUE TITLE
" issueベースの開発"レビュー依頼

### ISSUE THREAD

**Issue by miyataro0314** [miyataro0314/MotoTokyo#27]
### 実装予定の機能

- [ ] ユーザー登録
  - [ ] ユーザーID変更
  - [ ] メールアドレス変更
  - [ ] パスワード変更
  - [ ] アカウント削除
- [ ] スポット
  - [ ] 登録・詳細・編集・検索・削除
  - [ ] 登録はモーダル・ウィザードフォーム、検索はモーダル
  - [ ] ホームでは検索履歴からレコメンド
- [ ] スポットコメント
  - [ ] 登録・編集・一覧・削除
  - [ ] 全てモーダル表示
- [ ] スポットブックマーク
  - [ ] 追加・削除
- [ ] スポット評価（行きやすさ）
  - [ ] 投票
  - [ ] 投票割合の動的変化
- [ ] パーキング
  - [ ] 付近の駐車場取得
  - [ ] 登録している排気量によって利用可否表示
- [ ] プロフィール
  - [ ] ニックネーム・アバター
  - [ ] 愛車登録（排気量登録・写真）
- [ ] API
  - [ ] GoogleMap
    - [ ] スポット登録時、オートコンプリート
    - [ ] スポット投稿時、詳細取得
    - [ ] スポット・パーキング詳細表示時、マップ埋め込み
  - [ ] 天気予報API
    - [ ] スポット詳細画面、付近の習慣天気表示
- [ ] 管理画面
  - [ ] パーキング登録
  - [ ] スポット編集・削除
  - [ ] コメント削除

### 必要なページ
- [ ] 静的ページ
  - [ ] トップページ
  - [ ] アバウトページ
  - [ ] 利用規約
  - [ ] プライバシーポリシー
- [ ] ユーザー
  - [ ] 会員登録
  - [ ] ログイン
  - [ ] パスワードリセット
  - [ ] ユーザーID変更
  - [ ] メールアドレス変更
- [ ] スポット
  - [ ] ログイン後トップ（ホーム）
  - [ ] 登録トップ
  - [ ] 登録画面
  - [ ] 検索トップ
  - [ ] 検索画面
  - [ ] 検索結果
  - [ ] 詳細画面
  - [ ] 編集画面
- [ ] コメント
  - [ ] 一覧画面
  - [ ] 投稿・編集画面
- [ ] パーキング
  - [ ] 詳細画面 
- [ ] マイページ
  - [ ] プロフィールトップ
  - [ ] プロフィール編集画面
  - [ ] 友達一覧画面
  - [ ] 友達検索画面
- [ ] 管理画面
  - [ ] 駐車場登録
  - [ ] 駐車場一覧
  - [ ] 駐車場詳細
  - [ ] 駐車場編集
  - [ ] スポット一覧
  - [ ] スポット詳細
  - [ ] スポット編集
  - [ ] コメント一覧

**Comment by kenchasonakai** [comment]
LGTMです！
