### ISSUE TITLE
5/30 MVPリリースレビュー依頼

### ISSUE THREAD

**Issue by miyataro0314** [miyataro0314/MotoTokyo#55]
## 各種情報
サービス名：MotoTokyo
サービスURL：https://moto-tokyo.com/

## READMEレビュー時にMVPリリース時点で実装予定だった機能
- [x] ユーザー登録
  - [ ] ユーザーID変更
  - [ ] メールアドレス変更
  - [ ] パスワード変更
  - [ ] アカウント削除
- [x] スポット
  - [x] 登録・詳細・編集・検索・削除
  - [x] 登録はモーダル・ウィザードフォーム、検索はモーダル
  - [ ] ホームでは検索履歴からレコメンド
- [ ] スポットコメント
  - [ ] 登録・編集・一覧・削除
  - [ ] 全てモーダル表示
- [x] スポットブックマーク
  - [x] 追加・削除
- [ ] スポット評価（行きやすさ）
  - [x] 投票
  - [ ] 投票割合の動的変化
- [x] パーキング
  - [x] 付近の駐車場取得
  - [ ] ~~登録している排気量によって利用可否表示~~
- [x] プロフィール
  - [x] ニックネーム・アバター
  - [x] 愛車登録（排気量登録・写真）
- [ ] API
  - [x] GoogleMap
    - [x] スポット登録時、オートコンプリート
    - [x] スポット投稿時、詳細取得
    - [x] スポット・パーキング詳細表示時、マップ埋め込み
  - [ ] 天気予報API
    - [ ] スポット詳細画面、付近の習慣天気表示
- [x] 管理画面
  - [ ] ~~パーキング登録~~
  - [ ] スポット編集・削除
  - [ ] コメント削除

## READMEレビュー時から変更した機能
- 管理画面での駐車場登録機能を削除（そのため管理画面での機能は現時点では無し）
  → 駐車場登録はjsonで一括登録する方法に変更のため
- 排気量登録と、駐車場の利用可否表示機能の削除
  → 駐車場登録方法の変更に伴い実現不可
- 上記で未チェックのものはスケジュール見積もり面談時に『本リリース迄に実装』に変更したため、予定通りMVPリリース時点での実装は終了しています。

## サービスイメージがわかるようなスクリーンショット等
- トップページ
[![Image from Gyazo](https://i.gyazo.com/34c325e01b66c2161ae5b295e58ba4d1.png)](https://gyazo.com/34c325e01b66c2161ae5b295e58ba4d1)
- スポット登録
[![Image from Gyazo](https://i.gyazo.com/772980ba35fb61d0b1d144a5b431718b.png)](https://gyazo.com/772980ba35fb61d0b1d144a5b431718b)
- スポット詳細
[![Image from Gyazo](https://i.gyazo.com/e0f00835657895ab3481786e5c08b590.png)](https://gyazo.com/e0f00835657895ab3481786e5c08b590)
- スポット一覧
[![Image from Gyazo](https://i.gyazo.com/903e0b74fbd9d7f733a59d9b124123e9.png)](https://gyazo.com/903e0b74fbd9d7f733a59d9b124123e9)
- スポット検索
[![Image from Gyazo](https://i.gyazo.com/d224703fa35587ec82d15c10cbfdbb7d.png)](https://gyazo.com/d224703fa35587ec82d15c10cbfdbb7d)
- 駐車場詳細
[![Image from Gyazo](https://i.gyazo.com/93600db26ff75810e789b9522dcc9106.png)](https://gyazo.com/93600db26ff75810e789b9522dcc9106)
- マイスポット（ブックマーク）
[![Image from Gyazo](https://i.gyazo.com/fc926ec3eff48ad879891d33edb830f1.png)](https://gyazo.com/fc926ec3eff48ad879891d33edb830f1)
- マイスポット（登録したスポット）
[![Image from Gyazo](https://i.gyazo.com/7cd368f323c8b81145f978418eff00e3.png)](https://gyazo.com/7cd368f323c8b81145f978418eff00e3)
- マイページ
[![Image from Gyazo](https://i.gyazo.com/28c46dc3185f9dba13f7249bf51f4fc9.png)](https://gyazo.com/28c46dc3185f9dba13f7249bf51f4fc9)

**Comment by miyataro0314** [comment]
大変申し訳ございませんが、只今会員情報の認証漏れによりドメインが凍結されおり、おそらく繋がらない状態になっていると思います。
再承認の手続きを進めているのですが、少し時間がかかりそうです。
万が一レビュー時にも開通してなかった場合、一度差し戻し等していただければと思います。改善後に再度レビュー依頼いたします。
お手数おかけし申し訳ございません。

**Comment by miyataro0314** [comment]
上記ドメインの件、ただいま復旧できましたので問題なく開けるようになっているかと思います。
よろしくお願いします。

**Comment by Tsuchiya2** [comment]
Uploading 画面収録 2024-05-30 11.54.01.mov…


ユーザー登録の前から既にログイン？しているのか、ログアウトボタンが出ているのですが...ご確認いただけますか。

**Comment by miyataro0314** [comment]
大変失礼しました。
ユーザー登録前にログインしているわけではなく、ログイン状態での分岐をまだ組み込んでおりませんでした。
静的ページ作成時に整えるつもりだったのですが、この状態では不適切でしたので修正いたしました。
なおリンク先は現時点では未作成のため全て'#'にしております。
（ログイン後に非表示となるフッターの代替として用意している部分のため、リンク内容はフッターと一致させています。）
よろしくお願いします。
[![Image from Gyazo](https://i.gyazo.com/60d254b79e84f9b799b2c49b9b246cff.gif)](https://gyazo.com/60d254b79e84f9b799b2c49b9b246cff)

**Comment by shota-hope** [comment]
再提出ありがとうございます。
確認させていただきました。

- スポット
  - 編集、削除の動線がわかりませんでした。
- ユーザー
  - ユーザーIDを変更する
  - メールアドレス変更
    - 上記2つのボタンを押しても遷移しませんでした。（反応がありませんでした）
  - パスワード変更
    - すでにログインしています。とアラートがでました。
  
概要の機能一覧にチェックがはいっているその他機能は問題ありませんでした。
ご確認よろしくお願いします。

**Comment by miyataro0314** [comment]
お忙しい中ご確認ありがとうございます。
スポット編集・削除は自身が登録したスポットのみ可能のため、下記GIFの流れで行います。
スクリーンショット等の部分に載せておらず、確認のお手数おかけし申し訳ございません。
[![Image from Gyazo](https://i.gyazo.com/8bc53b7319f3debc875707e4355e4ea5.gif)](https://gyazo.com/8bc53b7319f3debc875707e4355e4ea5)

ユーザー関係、誤ってチェックを付けておりました。
issue名「アカウント情報」はMVPリリース後に実装予定の部分でおりますのでモックアップ画面のみ実装している状態です。

導線について、確かに分かりにくいと感じました。
また、現状スポット詳細からスポット名や住所をクリックすることでGoogleMapに飛べるようにしているのですが、これも分かりにくい部分でしたので、この辺りの操作方法についてはGIFで説明するページを作ることでUX向上を図りたいと思います。

**Comment by kenchasonakai** [comment]
LGTMです！

**Comment by miyataro0314** [comment]
レビューありがとうございます。クローズしMVPリリースいたします。
